### PR TITLE
Replace creature loot with appropriate one

### PR DESCRIPTION
**Pull request by Ychap**
In BGT and EET: RNDTRE04 => RNDTRE08
In BGEE and EET: AX1H03 (Battle Axe of Mauletar +2) => AX1H11 (Generic axe +2)

### CODE REVIEW

**Comment by Gitjas** [comment]
"Appropriate" is a matter of definition. We made the experience with Ascalon's Questpack that random BGII loot in the BG1 part leads to too powerful items.

**Comment by GraionDilach** [comment]
Then why are you rejecting this patch? On the Trilogy mods, RNDTRE04 is the BG2 WEALTHY random treasure, with RNDTRE08 being the BG1 counterpart.

Basically, this patch only substitutes the unique axe with a generic counterpart (so keep the unique one base-game only) and fixes the BG2 treasure leakage into BG1. It's a polish fix.

**Comment by Gitjas** [comment]
I didn't reject it, I don't understand the exact changes and didn't have tme to look into it. 
Thanks for the details.

**Comment by Gitjas** [comment]
I need more help to understand this. In my EET, there isn't a "RNDTRE08". I only find "SODTRE08" in the RNDTRES.2DA. I am confused. Where would I see what kind of loot "RNDTRE08" is substituted with?

**Comment by GraionDilach** [comment]
Yes, but you also need to look at RNDTREAS.2DA as well.

RNDTRES.2DA (without the A) was introduced by Beamdog for the IWD random treasure and works in parallel to the old system. By default in an RNDTRE0X filename, the X means the index of the row within RNDTREAS.2DA, and both BGT and EET expands this table with the BG1 duplicates first.

It is possible to insert the RNDTRE0X filenames to RNDTRES.2DA and randomize them there instead (SoD does this, but EET renames those to the SODTRE ones you found, both to free up the indices to mimic BGT instead and ensure that there's no accidental overlap between the two random tables).

Loosely related to this are Argent77's findings from years ago: https://forums.beamdog.com/discussion/comment/792223/#Comment_792223

**Comment by Ychap** [comment]
> I need more help to understand this. In my EET, there isn't a "RNDTRE08". I only find "SODTRE08" in the RNDTRES.2DA. I am confused. Where would I see what kind of loot "RNDTRE08" is substituted with?

Here is a full explanation, how RNDTREAS.2DA works: https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/rndtreas.htm

**Comment by Ychap** [comment]
Same kind of bug is also described in this PR: https://github.com/Gitjas/Ascalons_Questpack/pull/12

**Comment by Gitjas** [comment]
Very cool. Thank you all for the explanations. I didn't know where to look.

Ychap, thank you for the fix.

**Pull request merged**
